export const sidebarNavaigation: {
  src: string;
  alt: string;
}[] = [
  {
    src: "/assets/icons/home.svg",
    alt: "Home",
  },
  {
    src: "/assets/icons/users-group.svg",
    alt: "Users group",
  },
  {
    src: "/assets/icons/note.png",
    alt: "Notebook",
  },
  {
    src: "/assets/icons/share.svg",
    alt: "Share",
  },
  {
    src: "/assets/icons/file.svg",
    alt: "File",
  },
  {
    src: "/assets/icons/notebook.svg",
    alt: "notebook",
  },
  {
    src: "/assets/icons/heart.svg",
    alt: "heart",
  },
  {
    src: "/assets/icons/chevron-left.svg",
    alt: "chevron-left",
  },
];

export const filters: {
  fileSrc: string;
  fileAlt: string;
  caretDownSrc: string;
  caretDownAlt: string;
  label: string;
}[] = [
  {
    fileSrc: "/assets/icons/file.svg",
    fileAlt: "File",
    caretDownSrc: "/assets/icons/caret-down-md.svg",
    caretDownAlt: "Caret down",
    label: "Personal Information",
  },
  {
    fileSrc: "/assets/icons/file.svg",
    fileAlt: "File",
    caretDownSrc: "/assets/icons/caret-down-md.svg",
    caretDownAlt: "Caret down",
    label: "Education",
  },
  {
    fileSrc: "/assets/icons/file.svg",
    fileAlt: "File",
    caretDownSrc: "/assets/icons/caret-down-md.svg",
    caretDownAlt: "Caret down",
    label: "Work Experience",
  },
  {
    fileSrc: "/assets/icons/file.svg",
    fileAlt: "File",
    caretDownSrc: "/assets/icons/caret-down-md.svg",
    caretDownAlt: "Caret down",
    label: "Activity Filter",
  },

  {
    fileSrc: "/assets/icons/file.svg",
    fileAlt: "File",
    caretDownSrc: "/assets/icons/caret-down-md.svg",
    caretDownAlt: "Caret down",
    label: "Advanced Filter",
  },
];

export const statuses: string[] = [
  "applied",
  "shortlisted",
  "technical interview",
  "opportunity browsing",
  "video interview I",
  "video interview II",
  "video interview III",
  "other",
  "withdrawn",
];

export const userStatsToolbar: {
  src: string;
  alt: string;
}[] = [
  {
    src: "/assets/icons/tag.svg",
    alt: "tag",
  },
  {
    src: "/assets/icons/user-close.svg",
    alt: "user-close",
  },
  {
    src: "/assets/icons/user-check.svg",
    alt: "user-check",
  },
  {
    src: "/assets/icons/user-voice.svg",
    alt: "user-voice",
  },
  {
    src: "/assets/icons/mail.svg",
    alt: "mail",
  },
];

function getRandomStatus() {
  const statuses = [
    "applied",
    "shortlisted",
    "technical interview",
    "opportunity browsing",
    "video interview I",
    "video interview II",
    "video interview III",
    "other",
    "withdrawn",
  ];
  const randomIndex = Math.floor(Math.random() * statuses.length);
  return statuses[randomIndex];
}

function getApplicationStatus() {
  const statuses = ["qualified", "disqualified", "task"];
  const randomIndex = Math.floor(Math.random() * statuses.length);
  return statuses[randomIndex];
}
const firstNames: string[] = [
  "Liam",
  "Olivia",
  "Noah",
  "Emma",
  "Oliver",
  "Ava",
  "Elijah",
  "Charlotte",
  "William",
  "Sophia",
  "James",
  "Mia",
  "Benjamin",
  "Amelia",
  "Henry",
  "Harper",
  "Alexander",
  "Evelyn",
  "Samuel",
  "Abigail",
  "Ethan",
  "Emily",
  "Michael",
  "Elizabeth",
  "Daniel",
  "Sofia",
  "Matthew",
  "Avery",
  "David",
  "Ella",
  "Joseph",
  "Scarlett",
  "Jackson",
  "Grace",
  "Sebastian",
  "Chloe",
  "Jack",
  "Victoria",
  "Samuel",
  "Lily",
  "Gabriel",
  "Aria",
  "John",
  "Addison",
  "Luke",
  "Aubrey",
  "Isaac",
  "Lillian",
  "Christopher",
  "Natalie",
  "Joshua",
  "Zoe",
  "Andrew",
  "Leah",
  "Caleb",
  "Hazel",
  "Nathan",
  "Samantha",
  "Ryan",
  "Audrey",
  "Owen",
  "Zoey",
  "Daniel",
  "Penelope",
  "Isaac",
  "Riley",
  "Anthony",
  "Skylar",
  "Josiah",
  "Violet",
  "Julian",
  "Eleanor",
  "Leo",
  "Hannah",
  "Eli",
  "Stella",
  "John",
  "Aurora",
  "Henry",
  "Lucy",
  "Nicholas",
  "Bella",
  "Andrew",
  "Ellie",
  "Joshua",
  "Madison",
  "Levi",
  "Mila",
  "Christopher",
  "Claire",
  "Lincoln",
  "Naomi",
  "Jonathan",
  "Grace",
  "Jaxon",
  "Nora",
  "Julian",
  "Hazel",
  "Aaron",
  "Ruby",
];

const lastNames: string[] = [
  "Smith",
  "Johnson",
  "Brown",
  "Taylor",
  "Miller",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Martinez",
  "Jones",
  "Davis",
  "Garcia",
  "Rodriguez",
  "Martinez",
  "Wilson",
  "Lopez",
  "Lee",
  "Walker",
  "Hall",
  "Allen",
  "Young",
  "Hernandez",
  "King",
  "Wright",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Gonzalez",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Roberts",
  "Turner",
  "Phillips",
  "Campbell",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Sanchez",
  "Morris",
  "Rogers",
  "Reed",
  "Cook",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cox",
  "Cox",
  "Foster",
  "Reyes",
  "Mason",
  "Hunter",
  "Phillips",
  "Barnes",
  "Graham",
  "Reed",
  "Johnson",
  "Parker",
  "Butler",
  "Harris",
  "Martinez",
  "Walker",
  "Scott",
  "Hill",
  "Allen",
  "King",
  "Wright",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Turner",
  "Gonzalez",
  "Campbell",
  "Roberts",
  "Stewart",
  "Phillips",
  "Evans",
  "Cook",
  "Green",
  "Sanchez",
  "Howard",
  "Richardson",
  "Cooper",
  "Cox",
  "Cox",
  "Coleman",
  "Murphy",
  "Bailey",
  "Rivera",
  "Rogers",
  "Reed",
];

const locations: string[] = [
  "Riyadh, Saudi Arabia",
  "London, United Kingdom",
  "New York City, USA",
  "Tokyo, Japan",
  "Paris, France",
  "Sydney, Australia",
  "Los Angeles, USA",
  "Berlin, Germany",
  "Toronto, Canada",
  "Madrid, Spain",
  "Rome, Italy",
  "Beijing, China",
  "Seoul, South Korea",
  "Mumbai, India",
  "Dubai, United Arab Emirates",
  "Moscow, Russia",
  "Sao Paulo, Brazil",
  "Istanbul, Turkey",
  "Cairo, Egypt",
  "Buenos Aires, Argentina",
  "Amsterdam, Netherlands",
  "Stockholm, Sweden",
  "Singapore",
  "Hong Kong",
  "Vienna, Austria",
  "Athens, Greece",
  "Prague, Czech Republic",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Lisbon, Portugal",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Copenhagen, Denmark",
  "Brussels, Belgium",
  "Zurich, Switzerland",
  "Dublin, Ireland",
  "Mexico City, Mexico",
  "Ottawa, Canada",
  "Johannesburg, South Africa",
  "Melbourne, Australia",
  "Vancouver, Canada",
  "Calgary, Canada",
  "Montreal, Canada",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Santiago, Chile",
  "Bogota, Colombia",
  "Lima, Peru",
  "Quito, Ecuador",
  "Caracas, Venezuela",
  "Rio de Janeiro, Brazil",
  "Brasilia, Brazil",
  "Guatemala City, Guatemala",
  "San Salvador, El Salvador",
  "Tegucigalpa, Honduras",
  "Managua, Nicaragua",
  "San Jose, Costa Rica",
  "Panama City, Panama",
  "Kingston, Jamaica",
  "Havana, Cuba",
  "Nassau, Bahamas",
  "Santo Domingo, Dominican Republic",
  "Port-au-Prince, Haiti",
  "Bridgetown, Barbados",
  "Port of Spain, Trinidad and Tobago",
  "Georgetown, Guyana",
  "Paramaribo, Suriname",
  "Cayenne, French Guiana",
  "Belmopan, Belize",
  "Tijuana, Mexico",
  "Monterrey, Mexico",
  "Guadalajara, Mexico",
  "Cancun, Mexico",
  "Acapulco, Mexico",
  "Mazatlan, Mexico",
  "Chihuahua, Mexico",
  "Tampico, Mexico",
  "Merida, Mexico",
  "Veracruz, Mexico",
  "Oaxaca, Mexico",
  "Puebla, Mexico",
  "San Cristobal, Venezuela",
  "Maracaibo, Venezuela",
  "Valencia, Venezuela",
  "Barquisimeto, Venezuela",
  "San Juan, Puerto Rico",
  "Nassau, Bahamas",
  "Kingston, Jamaica",
  "Port of Spain, Trinidad and Tobago",
  "Bridgetown, Barbados",
  "Castries, Saint Lucia",
  "Georgetown, Guyana",
  "Paramaribo, Suriname",
  "Cayenne, French Guiana",
  "Belmopan, Belize",
  "Tegucigalpa, Honduras",
  "San Salvador, El Salvador",
  "Managua, Nicaragua",
  "San Jose, Costa Rica",
  "Panama City, Panama",
];

const universities: string[] = [
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology (MIT)",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University of California, Berkeley",
  "London School of Economics and Political Science (LSE)",
  "University of Chicago",
  "Princeton University",
  "California Institute of Technology (Caltech)",
  "Yale University",
  "University of Toronto",
  "University of Sydney",
  "University of Melbourne",
  "University of Tokyo",
  "University of Paris",
  "University of Berlin",
  "Peking University",
  "Seoul National University",
  "University of Mumbai",
  "American University of Dubai",
  "Lomonosov Moscow State University",
  "University of Sao Paulo",
  "Istanbul Technical University",
  "Cairo University",
  "University of Buenos Aires",
  "University of Amsterdam",
  "Stockholm University",
  "National University of Singapore (NUS)",
  "University of Hong Kong",
  "University of Vienna",
  "National and Kapodistrian University of Athens",
  "Charles University in Prague",
  "University of Warsaw",
  "Eotvos Lorand University, Budapest",
  "University of Lisbon",
  "University of Oslo",
  "University of Helsinki",
  "University of Copenhagen",
  "Universite libre de Bruxelles",
  "University of Zurich",
  "University of Vienna",
  "Trinity College Dublin",
  "University of Warsaw",
  "National Autonomous University of Mexico (UNAM)",
  "University of Ottawa",
  "University of the Witwatersrand",
  "University of Sydney",
  "University of Melbourne",
  "University of British Columbia",
];

const educations: string[] = [
  "Bachelor's in Computer Science",
  "Bachelor's in Business Administration (MBA)",
  "Bachelor's in Electrical Engineering",
  "Bachelor's in Data Science",
  "Bachelor's in Psychology",
  "Bachelor's in Public Health",
  "Bachelor's in Finance",
  "Bachelor's in Mechanical Engineering",
  "Bachelor's in Biology",
  "Bachelor's in Marketing",
  "Bachelor's in English Literature",
  "Bachelor's in Economics",
  "Bachelor's in Nursing",
  "Bachelor's in Information Technology",
  "Bachelor's in History",
  "Bachelor's in Environmental Science",
  "Bachelor's in Mathematics",
  "Bachelor's in Education",
  "Bachelor's in Political Science",
  "Bachelor's in Sociology",
  "Bachelor's in Civil Engineering",
  "Bachelor's in Psychology",
  "Bachelor's in Chemistry",
  "Bachelor's in Finance",
  "Bachelor's in Art History",
  "Bachelor's in Computer Engineering",
  "Bachelor's in Communications",
  "Bachelor's in Public Policy",
  "Bachelor's in Environmental Science",
  "Bachelor's in Human Resources",
  "Bachelor's in Economics",
  "Bachelor's in Electrical Engineering",
  "Bachelor's in Marketing",
  "Bachelor's in Nursing",
  "Bachelor's in Anthropology",
  "Bachelor's in History",
  "Bachelor's in Physics",
  "Bachelor's in Social Work",
  "Bachelor's in Sociology",
  "Bachelor's in Biology",
  "Bachelor's in Mechanical Engineering",
  "Bachelor's in Art History",
  "Bachelor's in Education",
  "Bachelor's in Political Science",
  "Bachelor's in Computer Engineering",
  "Bachelor's in Communications",
  "Bachelor's in Public Health",
  "Bachelor's in Chemistry",
  "Bachelor's in Human Resources",
];

const tags: string[] = [
  "Technology",
  "Finance",
  "Healthcare",
  "Engineering",
  "Art",
  "Science",
  "Entrepreneurship",
  "Education",
  "Business",
  "Design",
  "Music",
  "Sports",
  "Travel",
  "Fashion",
  "Food",
  "Environmental",
  "Social Media",
  "Entertainment",
  "Startups",
  "Research",
  "Gaming",
  "Photography",
  "Writing",
  "Film",
  "Fitness",
  "Astronomy",
  "Politics",
  "Languages",
  "History",
  "Philosophy",
  "Cuisine",
  "Theater",
  "Volunteering",
  "Cycling",
  "Hiking",
  "Yoga",
  "Dance",
  "Pets",
  "Reading",
  "Sustainability",
  "Artificial Intelligence",
  "Blockchain",
  "Virtual Reality",
  "Data Analytics",
  "Climate Change",
  "Space Exploration",
  "Health & Wellness",
  "Social Justice",
  "Environmental Conservation",
];

const getGraduationYear = () => {
  const gap = Math.random() < 0.5 ? 3 : 4;
  const startYear = Math.floor(Math.random() * (2023 - 2019 - gap + 1)) + 2019;
  const endYear = startYear + gap;
  return [`${startYear} - ${endYear}`, endYear];
};

const sampleData = [];

for (let i = 0; i < 100; i++) {
  const firstName = firstNames[i];
  const lastName = lastNames[i];
  const name = `${firstName} ${lastName}`;
  const location = locations[Math.floor(Math.random() * locations.length)];
  const education = educations[Math.floor(Math.random() * educations.length)];
  const university = universities[Math.floor(Math.random() * universities.length)];
  const [study_period, endYear] = getGraduationYear();
  const experience = 2023 - parseInt(endYear as string);
  const status = getRandomStatus();
  const applicationStatus = getApplicationStatus();
  const notes = "#top_candidate";
  const userTags = [];
  for (let j = 0; j < 3; j++) {
    const randomIndex = Math.floor(Math.random() * tags.length);
    userTags.push(tags[randomIndex]);
  }

  const dataObject = {
    id: i + 1,
    name,
    location,
    education,
    university,
    study_period,
    experience,
    status,
    applicationStatus,
    notes,
    tags: userTags,
  };

  sampleData.push(dataObject);
}

export const applicantsInfo = {
  internship_name: "London Internship Program",
  location: "London",
  total_applicants: 100,
  applicants: sampleData,
};
